### ISSUE TITLE
Crash issues

### ISSUE THREAD

**Issue by StormingMoon** [Spec-JohnXina/Vape-v4.16#3]
2024-12-17 16:25:07,564 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:25:07] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:25:07] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:25:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:25:07] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[16:25:07] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Utente\AppData\Roaming\.tlauncher\legacy\Minecraft\jre\jre-legacy\windows-x64\jre-legacy
[16:25:07] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:25:07] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:25:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:25:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:25:07] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:25:08] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:25:08] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:25:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:25:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:25:08] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:25:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:25:08] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2024-12-17 16:25:08,955 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2024-12-17 16:25:08,955 WARN Caught Exception while in Loader.getResource. This may be innocuous. java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:658)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at org.apache.logging.log4j.core.helpers.Loader.getResource(Loader.java:98)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromResource(ConfigurationFactory.java:300)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromString(ConfigurationFactory.java:280)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:380)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:377)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:149)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:85)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:322)
	at net.minecraft.client.Minecraft.<clinit>(Minecraft.java:193)
	at net.minecraft.client.main.Main.main(SourceFile:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

2024-12-17 16:25:08,971 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:25:09] [Client thread/INFO]: Setting user: Brieucrow
[16:25:10] [Client thread/INFO]: LWJGL Version: 2.9.4
[16:25:10] [Client thread/WARN]: =============================================================
[16:25:10] [Client thread/WARN]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[16:25:10] [Client thread/WARN]: Offendor: com/sun/jna/Native.main([Ljava/lang/String;)V
[16:25:10] [Client thread/WARN]: Use FMLCommonHandler.exitJava instead
[16:25:10] [Client thread/WARN]: =============================================================
[16:25:10] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 17.12.24. 16:25
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1868562416 bytes (1781 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 23 total; -Xverify:none -Xms2048M -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=200 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:+UseStringDeduplication -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 565.90' Renderer: 'NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2'
[16:25:10] [Client thread/INFO]: MinecraftForge v11.15.1.2318 Initialized
[16:25:10] [Client thread/INFO]: Replaced 229 ore recipies
[16:25:11] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[16:25:11] [Client thread/INFO]: Searching C:\Users\Administrator\AppData\Roaming\.tlauncher\legacy\Minecraft\game\mods for mods
[16:25:11] [Client thread/INFO]: Forge Mod Loader has identified 3 mods to load
[16:25:11] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[16:25:11] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[16:25:11] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[16:25:11] [Client thread/INFO]: Processing ObjectHolder annotations
[16:25:11] [Client thread/INFO]: Found 384 ObjectHolder annotations
[16:25:11] [Client thread/INFO]: Identifying ItemStackHolder annotations
[16:25:11] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[16:25:12] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[16:25:12] [Client thread/INFO]: Applying holder lookups
[16:25:12] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:25:12] [Client thread/INFO]: Holder lookups applied
[16:25:12] [Client thread/INFO]: Injecting itemstacks
[16:25:12] [Client thread/INFO]: Itemstack injection complete
[16:25:12] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:25:12] [Thread-9/INFO]: Initializing LWJGL OpenAL
[16:25:12] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:25:13] [Thread-9/INFO]: OpenAL initialized.
[16:25:13] [Sound Library Loader/INFO]: Sound engine started
[16:25:15] [Client thread/INFO]: Max texture size: 16384
[16:25:15] [Client thread/INFO]: Created: 16x16 textures-atlas
[16:25:16] [Client thread/INFO]: Injecting itemstacks
[16:25:16] [Client thread/INFO]: Itemstack injection complete
[16:25:16] [Client thread/INFO]: Forge Mod Loader has successfully loaded 3 mods
[16:25:16] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[16:25:16] [Client thread/INFO]: SoundSystem shutting down...
[16:25:16] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[16:25:16] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:25:16] [Thread-11/INFO]: Initializing LWJGL OpenAL
[16:25:16] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:25:16] [Thread-11/INFO]: OpenAL initialized.
[16:25:17] [Client thread/INFO]: Max texture size: 16384
[16:25:17] [Sound Library Loader/INFO]: Sound engine started
[16:25:17] [Client thread/INFO]: Created: 512x512 textures-atlas
[16:25:28] [Thread-13/INFO]: [cn.gov.vape.Entrypoint:getVersion:-2]: Detect v1.8.8
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: Failed allocate field: 44 ofFastRender IN net.minecraft.client.settings.GameSettings
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: Failed allocate field: 45 ofAaLevel IN net.minecraft.client.settings.GameSettings
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: 465
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: SOLID net.minecraft.util.EnumWorldBlockLayer Lnet/minecraft/util/EnumWorldBlockLayer; true true
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: Failed allocate field: 509 ofFastRender IN net.minecraft.client.settings.GameSettings
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getField:-2]: Failed allocate field: 510 ofAaLevel IN net.minecraft.client.settings.GameSettings
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getMethod:-2]: 465
[16:25:30] [Thread-13/INFO]: [cn.gov.vape.reflect.Reflections:getMethod:-2]: setPosition net.minecraft.entity.Entity (DDD)V false false
[16:25:30] [Thread-13/INFO]: [a.a:su:-2]: Brieucrow
[16:25:33] [Client thread/ERROR]: ########## GL ERROR ##########
[16:25:33] [Client thread/ERROR]: @ Post render
[16:25:33] [Client thread/ERROR]: 1280: Invalid enum
[16:25:34] [Thread-13/INFO]: [a.a:p:-2]: [1734449134106] --- UniversalItemManager Validation ---
[16:25:34] [Thread-13/INFO]: [a.a:p:-2]: [1734449134106] Failed to find 95 item(s):
[16:25:36] [Thread-13/INFO]: [a.a:dc:-2]: Method Called >> a::dc ()V called
pro 17, 2024 4:25:36 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Read packet with no bytes
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Read packet with no bytes
	at a.DZ.decode(DZ.java:8)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:208)
	... 16 more

[16:25:40] [Thread-27/INFO]: [a.a:gls:-2]: Method Called >> a::gls ()[Z called
[16:25:40] [Thread-27/INFO]: [a.a:p:-2]: [1734449140335] default has no online uuid
[16:25:40] [Server thread/INFO]: Starting integrated minecraft server version 1.8.9
[16:25:40] [Server thread/INFO]: Generating keypair
[16:25:40] [Server thread/INFO]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@6d4c7118)
[16:25:40] [Server thread/INFO]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@6d4c7118)
[16:25:40] [Server thread/INFO]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@6d4c7118)
[16:25:40] [Server thread/INFO]: Preparing start region for level 0
[16:25:41] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414) ~[dn.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47) ~[dn.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414) ~[dn.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47) ~[dn.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414) ~[dn.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47) ~[dn.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132) ~[dx.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[dx.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82) ~[dx.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92) ~[anj.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109) ~[ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109) ~[bpo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123) ~[bpo.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[16:25:41] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Administrator\AppData\Roaming\.tlauncher\legacy\Minecraft\game\crash-reports\crash-2024-12-17_16.25.41-server.txt
[16:25:41] [Server thread/INFO]: Applying holder lookups
[16:25:41] [Server thread/INFO]: Holder lookups applied
[16:25:41] [Server thread/INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:25:41] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----
// There are four lights!

Time: 17.12.24. 16:25
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1166991032 bytes (1112 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 23 total; -Xverify:none -Xms2048M -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=200 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UseG1GC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:+UseStringDeduplication -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32 -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 29, tallocated: 77
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[16:25:41] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Administrator\AppData\Roaming\.tlauncher\legacy\Minecraft\game\crash-reports\crash-2024-12-17_16.25.41-server.txt

pls fix i cant even inject into lunar

**Comment by StormingMoon** [comment]
on lunar it leaves nothing it doesnt crash but it doesnt go past the zkm splash screen

**Comment by JohnXina-spec** [comment]
any logs?

**Comment by StormingMoon** [comment]
no logs and this happens here so prob same issue on lunar

**Comment by JohnXina-spec** [comment]
check latest.log

**Comment by StormingMoon** [comment]
[latest.log](https://github.com/user-attachments/files/18168090/latest.log)
yea nothing

**Comment by StormingMoon** [comment]
![image](https://github.com/user-attachments/assets/4247a467-8a0d-4fc2-991c-9748f1c63032)
i made it work but please fix the forge bug its probably the reason ur support for clients is so bad
making it work on forge is a need

**Comment by JohnXina-spec** [comment]
fine, thanks
